// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45DY4-KkCJ5UxhacUmKToypqn3OtcT6Y',
    appId: '1:1057224801611:web:d691cb44c12334cdcfbcce',
    messagingSenderId: '1057224801611',
    projectId: 'fir-flutter-codelab-7a7d3',
    authDomain: 'fir-flutter-codelab-7a7d3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-7a7d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqaSXchq5Ak9n5LBnyAGNYJuqSeiU-6as',
    appId: '1:1057224801611:android:288f745b35c40f5acfbcce',
    messagingSenderId: '1057224801611',
    projectId: 'fir-flutter-codelab-7a7d3',
    storageBucket: 'fir-flutter-codelab-7a7d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL8u3LKWHHDE3654YV-BHsnrjXmhNhDbc',
    appId: '1:1057224801611:ios:a255535dbede3bb6cfbcce',
    messagingSenderId: '1057224801611',
    projectId: 'fir-flutter-codelab-7a7d3',
    storageBucket: 'fir-flutter-codelab-7a7d3.appspot.com',
    iosClientId: '1057224801611-lnleobl47m16q9gc7th0tr6am3o19526.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL8u3LKWHHDE3654YV-BHsnrjXmhNhDbc',
    appId: '1:1057224801611:ios:a255535dbede3bb6cfbcce',
    messagingSenderId: '1057224801611',
    projectId: 'fir-flutter-codelab-7a7d3',
    storageBucket: 'fir-flutter-codelab-7a7d3.appspot.com',
    iosClientId: '1057224801611-lnleobl47m16q9gc7th0tr6am3o19526.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
